testing bot indication feature

diff --git a/.github/workflows/down_infrastructure.yml b/.github/workflows/down_infrastructure.yml
--- a/.github/workflows/down_infrastructure.yml
+++ b/.github/workflows/down_infrastructure.yml
@@ -4,9 +4,9 @@ on:
   workflow_dispatch:
     inputs:
       environment:
-        description: 'Select environment to deploy (prod, dev)'
+        description: "Select environment to deploy (prod, dev)"
         required: true
-        default: 'dev'
+        default: "dev"
         type: choice
         options:
           - dev
@@ -29,43 +29,43 @@ jobs:
         working-directory: ${{ env.working-directory }}
 
     steps:
-    - name: Configure aws credentials
-      uses: aws-actions/configure-aws-credentials@v4
-      with:
-        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        aws-region: ${{ vars.AWS_REGION }}
+      - name: Configure aws credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ vars.AWS_REGION }}
 
-    - name: Checkout
-      uses: actions/checkout@v4
+      - name: Checkout
+        uses: actions/checkout@v4
 
-    - name: Setup Terraform
-      uses: hashicorp/setup-terraform@v3
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v3
 
-    - name: Select meeting configuration
-      run: |
-        echo "Selecting backend configuration for environment: dev"
-        BACKEND_FILE="/home/runner/work/meeting-service/meeting-service/${{ env.working-directory }}/${{ github.event.inputs.environment }}.backend"
-        if [[ ! -f "$BACKEND_FILE" ]]; then
-          echo "Error: Backend file $BACKEND_FILE does not exist."
-          exit 1
-        fi
-        echo "Using backend configuration: $BACKEND_FILE"
+      - name: Select meeting configuration
+        run: |
+          echo "Selecting backend configuration for environment: dev"
+          BACKEND_FILE="/home/runner/work/meeting-service/meeting-service/${{ env.working-directory }}/${{ github.event.inputs.environment }}.backend"
+          if [[ ! -f "$BACKEND_FILE" ]]; then
+            echo "Error: Backend file $BACKEND_FILE does not exist."
+            exit 1
+          fi
+          echo "Using backend configuration: $BACKEND_FILE"
 
-    - name: Select .tfvars file based on environment
-      run: |
-        echo "Selecting .tfvars file for environment: ${{ github.event.inputs.environment }}"
-        if [[ ! -f "/home/runner/work/meeting-service/meeting-service/${{ env.working-directory }}/${{ github.event.inputs.environment }}.tfvars" ]]; then
-          echo "Error: File ${{ github.event.inputs.environment }}.tfvars does not exist in /home/runner/work/meeting-service/meeting-service/${{ env.working-directory }}."
-          exit 1
-        fi
+      - name: Select .tfvars file based on environment
+        run: |
+          echo "Selecting .tfvars file for environment: ${{ github.event.inputs.environment }}"
+          if [[ ! -f "/home/runner/work/meeting-service/meeting-service/${{ env.working-directory }}/${{ github.event.inputs.environment }}.tfvars" ]]; then
+            echo "Error: File ${{ github.event.inputs.environment }}.tfvars does not exist in /home/runner/work/meeting-service/meeting-service/${{ env.working-directory }}."
+            exit 1
+          fi
 
-    - name: Terraform Init
-      run: |
-        terraform init -backend-config="/home/runner/work/meeting-service/meeting-service/${{ env.working-directory }}/${{ github.event.inputs.environment }}.backend" -reconfigure
+      - name: Terraform Init
+        run: |
+          terraform init -backend-config="/home/runner/work/meeting-service/meeting-service/${{ env.working-directory }}/${{ github.event.inputs.environment }}.backend" -reconfigure
 
-    - name: Terraform Format
-      run: terraform fmt -check
+      - name: Terraform Format
+        run: terraform fmt -check
 
-    - name: Terraform destroy
-      run: terraform destroy -auto-approve -input=false -var-file=${{ github.event.inputs.environment }}.tfvars
+      - name: Terraform destroy
+        run: terraform destroy -auto-approve -input=false -var-file=${{ github.event.inputs.environment }}.tfvars
